version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: intramart-postgres
    environment:
      POSTGRES_DB: intramart_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - intramart-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: intramart-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@intramart.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - intramart-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  intramart-network:
    driver: bridge
